[package]
name = "management"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.228"
uuid = { version = "1.18.1", features = ["v4"] }
reqwest = { version = "0.12.24", features = ["blocking", "json"]}

